### ISSUE TITLE
Line chart second Y axis

### ISSUE THREAD

**Issue by bvego** [gooddata/gooddata-react-components#1124]
As far as I can see there is no option to add a second axis and normalize the data points on the chart to respect their measure

Could it be possible to add it?

**Comment by bvego** [comment]
Solved by combochart 😅

**Comment by ivan-nejezchleb** [comment]
Hi, since version 6.1.0 there is part of Chart Configuration focused exactly on this. See [documentation](https://sdk.gooddata.com/gooddata-ui/docs/chart_config.html#configure-axes) for more details. Only selected chart types support this functionality. If you want to use different type of chart for each axis, look at [Combo Chart](https://sdk.gooddata.com/gooddata-ui/docs/combo_chart_component.html)
