### ISSUE TITLE
Components not rendering/working when using different proxy target (e.g., analytics.totvs.com.br)

### ISSUE THREAD

**Issue by guilhermefarto** [gooddata/gooddata-react-components#329]
Hello there.

I'm trying to create and run some react app using GoodData UI.

I followed the start tutorial, but can't get it to work.

My proxy configuration at package.json is:

```
"proxy": {
    "/gdc": {
      "changeOrigin": true,
      "cookieDomainRewrite": "localhost",
      "secure": false,
      "target": "http://analytics.totvs.com.br/"
    },
    "/*.html": {
      "changeOrigin": true,
      "secure": false,
      "target": "http://analytics.totvs.com.br/"
    }
  }
```

I changed the target to 'http://analytics.totvs.com.br/' instead of the original value 'https://secure.gooddata.com/'.

When I try to run the KPI example, I'm getting the following error:

![image](https://user-images.githubusercontent.com/7007095/40445980-0f2f22da-5ea4-11e8-9e6c-00ed35adcba8.png)

What am I doing wrong?

All the best,

**Comment by BugsBunny338** [comment]
Hello @guilhermefarto, try changing target to `https://analytics.totvs.com.br/` (note the `s` in `httpS`) and let me know if it works. Cheers, Jiri

**Comment by guilhermefarto** [comment]
Hello @BugsBunny338 .
I don't know why, but I'm getting 401 UNAUTHORIZED.
I've already changed my password (a couple of times) but still not working (even with https).

![image](https://user-images.githubusercontent.com/7007095/40542878-600288f0-5ff8-11e8-95db-6fc5fdd65a2d.png)

![image](https://user-images.githubusercontent.com/7007095/40542983-ca20cee0-5ff8-11e8-8c3b-a2501b3c2666.png)

I think is something related to the /localhost/gdc (maybe it is blocking some return of GoodData authorization services).

Could you try with my credentials and config to "https://analytics.totvs.com.br"?

**Comment by BugsBunny338** [comment]
Hello @guilhermefarto, I do not know your credentials. If you could please invite me (jiri.zajic@gooddata.com) to your project (Manage --> Project & Users --> Invite Users), that would be really helpful. Thanks in advance, Jiri

**Comment by guilhermefarto** [comment]
Hello @BugsBunny338 . Alright!

I tried to send you an invite, but I'm getting a message: "User jiri.zajic@gooddata.com could not be invited because they are a member of another organization." (because you're not a TOTVS member).

Do you have a Gmail? I can try to send to you.

Just let me know if you need some more information.

I'm also sharing with you the project using GoodData.UI (in attachments) - so you can try to execute.
GoodData.UI is very impressive and I can't wait to see it working with our TOTVS' projects.

[my-first-sba.zip (project)](https://github.com/gooddata/gooddata-react-components/files/2041587/my-first-sba.zip)

All the best,

**Comment by guilhermefarto** [comment]
@BugsBunny338 , any news? All the best,

**Comment by jmachan** [comment]
Hello @guilhermefarto! Sorry for late response, our GoodData.UI SDK development team is on it and will let you know asap!

**Comment by zbycz** [comment]
Hi @guilhermefarto, 
thanks for sending your app in zip - it helped me debug this case. 
- I suppose that you are following the tutorial [First visualization](https://sdk.gooddata.com/gooddata-ui/docs/ht_create_your_first_visualization.html)

- please set `headers.host` in your `package.json` to `"analytics.totvs.com.br"`.
  *(Explanation: you received 401 Unauthorized, because the `/gdc` proxy forwared your login request to the `headers.host` parameter - in your case `secure.gooddata.com`)*

- btw, i saw that you use react 15.3.2, to work with react-components 5.x, please upgrade to 15.6.2 according to Step 2.3 in tutorial

- also, be sure to run your react app in local https mode (ie. `set HTTPS=true&&npm start` on windows) - check that your browsers ask for local certificate exception and then displays https version, that is https://localhost:3000

Thanks for your compliment, we are happy to make GoodData.UI work for you. :-) If any issue occur, be sure to share with us!

Kind regards,
Pavel

**Comment by jmachan** [comment]
Hi @guilhermefarto is everything working now? Let us know!

**Comment by guilhermefarto** [comment]
Hello @jmachan and @BugsBunny338 , how are you doing?
Yes, I'm testing some implementations, but I have already achieved some positive results.
Thank you!
