### ISSUE TITLE
British Columbia is not a State

### ISSUE THREAD

**Issue by lazaruslarue** [gooddata/gooddata-react-components#807]
https://local.test:8443/alpha-analytics/ab/overview

![image](https://user-images.githubusercontent.com/1894215/53600510-5c739c80-3b6f-11e9-8752-59ff6f04e40f.png)

![image](https://user-images.githubusercontent.com/1894215/53600530-6a292200-3b6f-11e9-896e-5b39415cd6c6.png)

**Comment by ivan-nejezchleb** [comment]
Hi, the link you provided is not working for me, unknown domain.
The inconsistency you reported is in data itself. Gooddata.UI provides only access to the data and way how to visualize it. It doesn't define the data values.

What is the data project you are working with? If it is your private project, than you need to fix this issue in your data. Otherwise try to contact admin of the project
